---
abstract: 'DO NOT USE THIS DIRECTLY.  USE THE PROVIDED ROLES INSTEAD!!!'
author:
  - 'Richard de Borja <richard.deborja@sickkids.ca>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: NGS-Tools-Mutect
provides:
  NGS::Tools::Mutect:
    file: lib/NGS/Tools/Mutect.pm
    version: 0.03
  NGS::Tools::Mutect::Role:
    file: lib/NGS/Tools/Mutect/Role.pm
    version: 0
requires:
  Moose: 2
  Moose::Role: 2
  MooseX::Params::Validate: 0
resources:
  license: http://opensource.org/licenses/artistic-license-2.0.php
version: 0.03
